name: Build on Linux

on: push

jobs:
  build-linux:
    name: Build On Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install linuxdeploy
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: qt appimage
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.12.10
          target: desktop
      - name: Install dependency
        run: sudo apt-get install cmake build-essential
      - name: Build with cmake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          build-type: Release
          configure-options:
          parallel: 2
      - name: Install Project
        run: |
          mkdir AppDir
          make install INSTALL_ROOT=${{runner.workspace}}/build/AppDir
        working-directory: ${{runner.workspace}}/build
      - name: Package Project
        run: |
          linuxdeploy-x86_64.AppImage --appdir ./AppDir --plugin qt --output appimage
        working-directory: ${{runner.workspace}}/build

